package com.valuescreener.research;

public enum ResearchCriterion {
    PE_RATIO,
    PB_RATIO,
    FIVE_YEAR_AVERAGE_PE,
    FIVE_YEAR_AVERAGE_PB,
    ROE,
    DEBT_TO_EQUITY,
    CURRENT_RATIO,
    CURRENT_YEAR_NET_MARGIN,
    CURRENT_YEAR_FCF_POSITIVE,
    CURRENT_YEAR_NET_INCOME_GREW,
    INSIDER_OWNERSHIP_SHARE,
    MARGIN_TREND,
    FREE_CASH_FLOW_TREND,
    PROFIT_STABILITY,
    INTEREST_COVERAGE,
    MOAT_ASSESSMENT,
    MANAGEMENT_QUALITY,
    VALUE_TRAP_ASSESSMENT
}
